// GENERATED by packages/argent/scripts/bundle-tools.cjs, which overwrites this
// file from argent-private's PERFETTO_VERSION; the committed value is a fallback
// so builds without that submodule still compile. Informational only — it stamps
// the bundled `trace_processor.wasm`, nothing resolves against it.

export const PERFETTO_VERSION = "v55.3";
