import { Registry } from "@argent/registry";
import { simulatorServerBlueprint } from "../blueprints/simulator-server";
import { jsRuntimeDebuggerBlueprint } from "../blueprints/js-runtime-debugger";
import { profilerSessionBlueprint } from "../blueprints/profiler-session";
import { listSimulatorsTool } from "../tools/simulator/list-simulators";
import { bootSimulatorTool } from "../tools/simulator/boot-simulator";
import { simulatorServerTool } from "../tools/simulator/simulator-server";
import { launchAppTool } from "../tools/simulator/launch-app";
import { restartAppTool } from "../tools/simulator/restart-app";
import { reinstallAppTool } from "../tools/simulator/reinstall-app";
import { openUrlTool } from "../tools/simulator/open-url";
import { screenshotTool } from "../tools/interactions/screenshot";
import { tapTool } from "../tools/interactions/tap";
import { swipeTool } from "../tools/interactions/swipe";
import { gestureTool } from "../tools/interactions/gesture";
import { buttonTool } from "../tools/interactions/button";
import { keyboardTool } from "../tools/interactions/keyboard";
import { rotateTool } from "../tools/simulator/rotate";
import { debuggerConnectTool } from "../tools/debugger/debugger-connect";
import { debuggerStatusTool } from "../tools/debugger/debugger-status";
import { debuggerEvaluateTool } from "../tools/debugger/debugger-evaluate";
import { debuggerSetBreakpointTool } from "../tools/debugger/debugger-set-breakpoint";
import { debuggerRemoveBreakpointTool } from "../tools/debugger/debugger-remove-breakpoint";
import { debuggerPauseTool } from "../tools/debugger/debugger-pause";
import { debuggerResumeTool } from "../tools/debugger/debugger-resume";
import { debuggerReloadMetroTool } from "../tools/debugger/debugger-reload-metro";
import { debuggerStepTool } from "../tools/debugger/debugger-step";
import { debuggerComponentTreeTool } from "../tools/debugger/debugger-component-tree";
import { debuggerInspectElementTool } from "../tools/debugger/debugger-inspect-element";
import { debuggerConsoleLogsTool } from "../tools/debugger/debugger-console-logs";
import { debuggerConsoleListenTool } from "../tools/debugger/debugger-console-listen";
import { describeTool } from "../tools/interactions/describe";
import { activateLicenseKeyTool } from "../tools/license/activate-license-key";
import { activateSsoTool } from "../tools/license/activate-sso";
import { getLicenseStatusTool } from "../tools/license/get-license-status";
import { removeLicenseTool } from "../tools/license/remove-license";
import { profilerStartTool } from "../tools/profiler/profiler-start";
import { profilerStopTool } from "../tools/profiler/profiler-stop";
import { profilerAnalyzeTool } from "../tools/profiler/profiler-analyze";
import { profilerComponentSourceTool } from "../tools/profiler/profiler-component-source";
import { profilerCpuSummaryTool } from "../tools/profiler/profiler-cpu-summary";
import { profilerReactRendersTool } from "../tools/profiler/profiler-react-renders";
import { profilerFiberTreeTool } from "../tools/profiler/profiler-fiber-tree";
import { profilerConsoleLogsTool } from "../tools/profiler/profiler-console-logs";
import { getLibraryDescriptionTool } from "../tools/ai/get-library-description";
import { queryDocumentationTool } from "../tools/ai/query-documentation";

export function createRegistry(): Registry {
  const registry = new Registry();

  registry.registerBlueprint(simulatorServerBlueprint);
  registry.registerBlueprint(jsRuntimeDebuggerBlueprint);
  registry.registerBlueprint(profilerSessionBlueprint);

  registry.registerTool(listSimulatorsTool);
  registry.registerTool(bootSimulatorTool);
  registry.registerTool(launchAppTool);
  registry.registerTool(restartAppTool);
  registry.registerTool(reinstallAppTool);
  registry.registerTool(openUrlTool);
  registry.registerTool(simulatorServerTool);
  registry.registerTool(screenshotTool);
  registry.registerTool(tapTool);
  registry.registerTool(swipeTool);
  registry.registerTool(gestureTool);
  registry.registerTool(buttonTool);
  registry.registerTool(keyboardTool);
  registry.registerTool(rotateTool);
  registry.registerTool(debuggerConnectTool);
  registry.registerTool(debuggerStatusTool);
  registry.registerTool(debuggerEvaluateTool);
  registry.registerTool(debuggerSetBreakpointTool);
  registry.registerTool(debuggerRemoveBreakpointTool);
  registry.registerTool(debuggerPauseTool);
  registry.registerTool(debuggerResumeTool);
  registry.registerTool(debuggerReloadMetroTool);
  registry.registerTool(debuggerStepTool);
  registry.registerTool(debuggerComponentTreeTool);
  registry.registerTool(debuggerInspectElementTool);
  registry.registerTool(debuggerConsoleLogsTool);
  registry.registerTool(debuggerConsoleListenTool);
  registry.registerTool(describeTool);
  registry.registerTool(activateLicenseKeyTool);
  registry.registerTool(activateSsoTool);
  registry.registerTool(getLicenseStatusTool);
  registry.registerTool(removeLicenseTool);
  registry.registerTool(profilerStartTool);
  registry.registerTool(profilerStopTool);
  registry.registerTool(profilerAnalyzeTool);
  registry.registerTool(profilerComponentSourceTool);
  registry.registerTool(profilerCpuSummaryTool);
  registry.registerTool(profilerReactRendersTool);
  registry.registerTool(profilerFiberTreeTool);
  registry.registerTool(profilerConsoleLogsTool);
  registry.registerTool(getLibraryDescriptionTool);
  registry.registerTool(queryDocumentationTool);

  return registry;
}
