import { Registry } from "@argent/registry";
import { simulatorServerBlueprint } from "../blueprints/simulator-server";
import { jsRuntimeDebuggerBlueprint } from "../blueprints/js-runtime-debugger";
import { reactProfilerSessionBlueprint } from "../blueprints/react-profiler-session";
import { listSimulatorsTool } from "../tools/simulator/list-simulators";
import { bootSimulatorTool } from "../tools/simulator/boot-simulator";
import { simulatorServerTool } from "../tools/simulator/simulator-server";
import { launchAppTool } from "../tools/simulator/launch-app";
import { restartAppTool } from "../tools/simulator/restart-app";
import { reinstallAppTool } from "../tools/simulator/reinstall-app";
import { openUrlTool } from "../tools/simulator/open-url";
import { screenshotTool } from "../tools/interactions/screenshot";
import { tapTool } from "../tools/interactions/tap";
import { swipeTool } from "../tools/interactions/swipe";
import { gestureTool } from "../tools/interactions/gesture";
import { buttonTool } from "../tools/interactions/button";
import { keyboardTool } from "../tools/interactions/keyboard";
import { rotateTool } from "../tools/simulator/rotate";
import { debuggerConnectTool } from "../tools/debugger/debugger-connect";
import { debuggerStatusTool } from "../tools/debugger/debugger-status";
import { debuggerEvaluateTool } from "../tools/debugger/debugger-evaluate";
import { debuggerSetBreakpointTool } from "../tools/debugger/debugger-set-breakpoint";
import { debuggerRemoveBreakpointTool } from "../tools/debugger/debugger-remove-breakpoint";
import { debuggerPauseTool } from "../tools/debugger/debugger-pause";
import { debuggerResumeTool } from "../tools/debugger/debugger-resume";
import { debuggerReloadMetroTool } from "../tools/debugger/debugger-reload-metro";
import { debuggerStepTool } from "../tools/debugger/debugger-step";
import { debuggerComponentTreeTool } from "../tools/debugger/debugger-component-tree";
import { debuggerInspectElementTool } from "../tools/debugger/debugger-inspect-element";
import { debuggerConsoleLogsTool } from "../tools/debugger/debugger-console-logs";
import { debuggerConsoleListenTool } from "../tools/debugger/debugger-console-listen";
import { describeTool } from "../tools/interactions/describe";
import { activateLicenseKeyTool } from "../tools/license/activate-license-key";
import { activateSsoTool } from "../tools/license/activate-sso";
import { getLicenseStatusTool } from "../tools/license/get-license-status";
import { removeLicenseTool } from "../tools/license/remove-license";
import { reactProfilerStartTool } from "../tools/profiler/react/react-profiler-start";
import { reactProfilerStopTool } from "../tools/profiler/react/react-profiler-stop";
import { reactProfilerAnalyzeTool } from "../tools/profiler/react/react-profiler-analyze";
import { reactProfilerComponentSourceTool } from "../tools/profiler/react/react-profiler-component-source";
import { reactProfilerCpuSummaryTool } from "../tools/profiler/react/react-profiler-cpu-summary";
import { reactProfilerRendersTool } from "../tools/profiler/react/react-profiler-renders";
import { reactProfilerFiberTreeTool } from "../tools/profiler/react/react-profiler-fiber-tree";
import { iosInstrumentsStartTool } from "../tools/profiler/ios-instruments/ios-instruments-start";
import { iosInstrumentsStopTool } from "../tools/profiler/ios-instruments/ios-instruments-stop";
import { iosInstrumentsAnalyzeTool } from "../tools/profiler/ios-instruments/ios-instruments-analyze";
import { iosInstrumentsSessionBlueprint } from "../blueprints/ios-instruments-session";
import { profilerCpuQueryTool } from "../tools/profiler/query/profiler-cpu-query";
import { profilerCommitQueryTool } from "../tools/profiler/query/profiler-commit-query";
import { profilerStackQueryTool } from "../tools/profiler/query/profiler-stack-query";
import { profilerCombinedReportTool } from "../tools/profiler/combined/profiler-combined-report";
import { createStopSimulatorServerTool } from "../tools/simulator/stop-simulator-server";
import { createStopAllSimulatorServersTool } from "../tools/simulator/stop-all-simulator-servers";
import { stopMetroTool } from "../tools/simulator/stop-metro";

export function createRegistry(): Registry {
  const registry = new Registry();

  registry.registerBlueprint(simulatorServerBlueprint);
  registry.registerBlueprint(jsRuntimeDebuggerBlueprint);
  registry.registerBlueprint(reactProfilerSessionBlueprint);
  registry.registerBlueprint(iosInstrumentsSessionBlueprint);

  registry.registerTool(listSimulatorsTool);
  registry.registerTool(bootSimulatorTool);
  registry.registerTool(launchAppTool);
  registry.registerTool(restartAppTool);
  registry.registerTool(reinstallAppTool);
  registry.registerTool(openUrlTool);
  registry.registerTool(simulatorServerTool);
  registry.registerTool(screenshotTool);
  registry.registerTool(tapTool);
  registry.registerTool(swipeTool);
  registry.registerTool(gestureTool);
  registry.registerTool(buttonTool);
  registry.registerTool(keyboardTool);
  registry.registerTool(rotateTool);
  registry.registerTool(debuggerConnectTool);
  registry.registerTool(debuggerStatusTool);
  registry.registerTool(debuggerEvaluateTool);
  registry.registerTool(debuggerSetBreakpointTool);
  registry.registerTool(debuggerRemoveBreakpointTool);
  registry.registerTool(debuggerPauseTool);
  registry.registerTool(debuggerResumeTool);
  registry.registerTool(debuggerReloadMetroTool);
  registry.registerTool(debuggerStepTool);
  registry.registerTool(debuggerComponentTreeTool);
  registry.registerTool(debuggerInspectElementTool);
  registry.registerTool(debuggerConsoleLogsTool);
  registry.registerTool(debuggerConsoleListenTool);
  registry.registerTool(describeTool);
  registry.registerTool(activateLicenseKeyTool);
  registry.registerTool(activateSsoTool);
  registry.registerTool(getLicenseStatusTool);
  registry.registerTool(removeLicenseTool);
  registry.registerTool(reactProfilerStartTool);
  registry.registerTool(reactProfilerStopTool);
  registry.registerTool(reactProfilerAnalyzeTool);
  registry.registerTool(reactProfilerComponentSourceTool);
  registry.registerTool(reactProfilerCpuSummaryTool);
  registry.registerTool(reactProfilerRendersTool);
  registry.registerTool(reactProfilerFiberTreeTool);
  registry.registerTool(iosInstrumentsStartTool);
  registry.registerTool(iosInstrumentsStopTool);
  registry.registerTool(iosInstrumentsAnalyzeTool);
  registry.registerTool(profilerCpuQueryTool);
  registry.registerTool(profilerCommitQueryTool);
  registry.registerTool(profilerStackQueryTool);
  registry.registerTool(profilerCombinedReportTool);

  // Cleanup tools (close over registry for direct service disposal)
  registry.registerTool(createStopSimulatorServerTool(registry));
  registry.registerTool(createStopAllSimulatorServersTool(registry));
  registry.registerTool(stopMetroTool);

  return registry;
}
