// Generated by packages/tool-server/test/sdk-tool-args.test.ts. Do not edit.

export interface ArgentToolArgs {
  "await-screen-idle": {
    udid: string;
    timeoutMs?: number;
    pollIntervalMs?: number;
    minStableMs?: number;
  };
  "await-ui-element": {
    udid: string;
    condition: "exists" | "visible" | "hidden" | "text";
    selector: { text?: string; identifier?: string; role?: string };
    expectedText?: string;
    textMatch?: "contains" | "equals";
    bundleId?: string;
    timeoutMs?: number;
    pollIntervalMs?: number;
  };
  "await_user_selection": { timeoutSeconds?: number };
  "boot-device": {
    udid?: string;
    avdName?: string;
    vvdImage?: string;
    bootTimeoutMs?: number;
    force?: boolean;
    sound?: boolean;
    headless?: boolean;
    electronAppPath?: string;
    electronPort?: number;
    electronArgs?: Array<string>;
  };
  "button": {
    udid: string;
    button: "home" | "back" | "power" | "volumeUp" | "volumeDown" | "appSwitch" | "actionButton";
  };
  "chromium-cookies": {
    udid: string;
    action: "get" | "set" | "delete" | "clear";
    name?: string;
    value?: string;
    url?: string;
    domain?: string;
    path?: string;
    secure?: boolean;
    httpOnly?: boolean;
    sameSite?: "Strict" | "Lax" | "None";
    expires?: number;
  };
  "chromium-storage": {
    udid: string;
    store: "local" | "session";
    action: "get" | "set" | "remove" | "clear";
    key?: string;
    value?: string;
  };
  "chromium-tabs": {
    udid: string;
    action: "list" | "select" | "new" | "close";
    tab?: string;
    url?: string;
    label?: string;
  };
  "debugger-component-tree": {
    port?: number;
    device_id: string;
    udid?: string;
    onScreenOnly?: boolean;
    maxNodes?: number;
    includeSkipped?: boolean;
  };
  "debugger-connect": { port?: number; device_id: string };
  "debugger-evaluate": { port?: number; device_id: string; expression: string };
  "debugger-inspect-element": {
    port?: number;
    device_id: string;
    x: number;
    y: number;
    contextLines?: number;
    resolveSourceMaps?: boolean;
    maxItems?: number;
    includeSkipped?: boolean;
  };
  "debugger-log-registry": { port?: number; device_id: string };
  "debugger-reload-metro": { port?: number; device_id: string };
  "debugger-status": { port?: number; device_id: string };
  "describe": { udid: string; bundleId?: string };
  "dismiss-update": { hours: number };
  "flow-add-echo": { name: string; project_root: string; message: string };
  "flow-add-script": { name: string; project_root: string; path: string; timeout?: number };
  "flow-add-step": {
    name: string;
    project_root: string;
    command: string;
    args?: string;
    delayMs?: number;
  };
  "flow-execute": {
    name?: string;
    project_root: string;
    flow_file?: string;
    flow_path?: string;
    device?: string;
    platform?: "ios" | "android" | "chromium" | "vega" | "ios-remote";
    updateBaselines?: boolean;
    prerequisiteAcknowledged?: boolean;
  };
  "flow-finish-recording": { name: string; project_root: string };
  "flow-read-prerequisite": {
    name?: string;
    project_root: string;
    flow_file?: string;
    flow_path?: string;
  };
  "flow-start-recording": { name: string; project_root: string; executionPrerequisite?: string };
  "fold": { udid: string; posture?: "closed" | "half-open" | "open"; angle?: number };
  "gather-workspace-data": { workspacePath: string };
  "gesture-custom": {
    udid: string;
    events: Array<{
      type: "Down" | "Move" | "Up";
      x: number;
      y: number;
      x2?: number;
      y2?: number;
      delayMs?: number;
    }>;
    interpolate?: number;
  };
  "gesture-drag": {
    udid: string;
    fromX: number;
    fromY: number;
    toX: number;
    toY: number;
    durationMs?: number;
    momentum?: boolean;
  };
  "gesture-pinch": {
    udid: string;
    centerX: number;
    centerY: number;
    startDistance: number;
    endDistance: number;
    endCenterX?: number;
    endCenterY?: number;
    angle?: number;
    durationMs?: number;
  };
  "gesture-rotate": {
    udid: string;
    centerX: number;
    centerY: number;
    radius?: number;
    radiusX?: number;
    radiusY?: number;
    startAngle: number;
    endAngle: number;
    durationMs?: number;
  };
  "gesture-scroll": {
    udid: string;
    x: number;
    y: number;
    deltaX?: number;
    deltaY?: number;
    durationMs?: number;
  };
  "gesture-swipe": {
    udid: string;
    fromX: number;
    fromY: number;
    toX: number;
    toY: number;
    durationMs?: number;
    momentum?: boolean;
  };
  "gesture-tap": { udid: string; x: number; y: number; clickCount?: number };
  "keyboard": { udid: string; text?: string; key?: string; delayMs?: number };
  "launch-app": { udid: string; bundleId: string; activity?: string };
  "list-devices": Record<string, never>;
  "native-describe-screen": {
    udid: string;
    bundleId: string;
    skipClasses?: Array<string>;
    skipClassPrefixes?: Array<string>;
  };
  "native-devtools-status": { udid: string; bundleId: string };
  "native-find-views": {
    udid: string;
    bundleId: string;
    className?: string;
    identifier?: string;
    label?: string;
    tag?: number;
    nativeID?: string;
    includeAncestors?: boolean;
    includeChildren?: boolean;
    fields?: Array<string>;
  };
  "native-full-hierarchy": {
    udid: string;
    bundleId: string;
    fields?: Array<string>;
    skipClasses?: Array<string>;
    skipClassPrefixes?: Array<string>;
    maxDepth?: number;
  };
  "native-network-logs": { udid: string; bundleId: string; limit?: number; clear?: boolean };
  "native-profiler-analyze": { device_id: string };
  "native-profiler-start": {
    device_id: string;
    app_process?: string;
    template_path?: string;
    malloc_stack_logging?: boolean;
  };
  "native-profiler-stop": { device_id: string };
  "native-user-interactable-view-at-point": {
    udid: string;
    bundleId: string;
    x: number;
    y: number;
    includeAncestors?: boolean;
    includeChildren?: boolean;
    fields?: Array<string>;
    skipClasses?: Array<string>;
    skipClassPrefixes?: Array<string>;
    maxDepth?: number;
  };
  "native-view-at-point": {
    udid: string;
    bundleId: string;
    x: number;
    y: number;
    includeAncestors?: boolean;
    includeChildren?: boolean;
    fields?: Array<string>;
    skipClasses?: Array<string>;
    skipClassPrefixes?: Array<string>;
    maxDepth?: number;
  };
  "open-url": { udid: string; url: string; bundleId?: string };
  "paste": { udid: string; text: string };
  "profiler-combined-report": { port?: number; device_id: string };
  "profiler-commit-query": {
    port?: number;
    device_id: string;
    mode: "by_component" | "by_time_range" | "by_index" | "cascade_tree";
    component_name?: string;
    time_range_ms?: { start: number; end: number };
    commit_index?: number;
    top_n?: number;
  };
  "profiler-cpu-query": {
    port?: number;
    device_id: string;
    mode: "top_functions" | "time_window" | "call_tree" | "component_cpu";
    time_window_ms?: { start: number; end: number };
    component_name?: string;
    function_name?: string;
    top_n?: number;
    include_callers?: boolean;
  };
  "profiler-load": {
    mode: "list" | "load_react" | "load_native";
    session_id?: string;
    port?: number;
    device_id: string;
    app_process?: string;
  };
  "profiler-stack-query": {
    device_id: string;
    mode: "hang_stacks" | "function_callers" | "thread_breakdown" | "leak_stacks";
    hang_index?: number;
    function_name?: string;
    thread?: string;
    object_type?: string;
    top_n?: number;
  };
  "propose_variant": {
    element: string;
    udid?: string;
    match?: { by: "text" | "label" | "identifier" | "role"; value: string };
    variant: {
      name: string;
      summary: string;
      code?: string;
      filePath?: string;
      previewImage: string;
      frame?: { x: number; y: number; width: number; height: number };
    };
  };
  "react-profiler-analyze": {
    port?: number;
    device_id: string;
    project_root: string;
    platform?: "ios" | "android";
    rn_version?: string;
    annotations?: Array<{ offsetMs: number; label: string }>;
  };
  "react-profiler-component-source": { component_name: string; project_root: string };
  "react-profiler-cpu-summary": {
    port?: number;
    device_id: string;
    top_n?: number;
    react_only?: boolean;
  };
  "react-profiler-fiber-tree": {
    port?: number;
    device_id: string;
    max_depth?: number;
    filter?: string;
  };
  "react-profiler-renders": { port?: number; device_id: string; top_n?: number };
  "react-profiler-start": {
    port?: number;
    device_id: string;
    sample_interval_us?: number;
    force?: boolean;
  };
  "react-profiler-status": { port?: number; device_id: string };
  "react-profiler-stop": { port?: number; device_id: string };
  "reinstall-app": { udid: string; bundleId: string; appPath: string };
  "restart-app": { udid: string; bundleId: string; activity?: string };
  "rotate": {
    udid: string;
    orientation: "Portrait" | "LandscapeLeft" | "LandscapeRight" | "PortraitUpsideDown";
  };
  "run-sequence": {
    udid: string;
    steps: Array<{ tool: string; args: { [key: string]: unknown }; delayMs?: number }>;
  };
  "screen-recording-start": {
    udid: string;
    timeLimitSeconds?: number;
    trimStatic?: boolean;
    showTouches?: boolean;
  };
  "screen-recording-stop": { udid: string };
  "screenshot": {
    udid: string;
    rotation?: "Portrait" | "LandscapeLeft" | "LandscapeRight" | "PortraitUpsideDown";
    scale?: number;
    includeImageInContext?: boolean;
    downscaler?: "lanczos3" | "box" | "bilinear" | "nearest";
  };
  "screenshot-diff": {
    baselinePath?: string;
    currentPath?: string;
    udid: string;
    captureBaseline?: boolean;
    captureCurrent?: boolean;
    rotation?: "Portrait" | "LandscapeLeft" | "LandscapeRight" | "PortraitUpsideDown";
    outputDir?: string;
  };
  "settings-permissions": {
    udid: string;
    action: "grant" | "deny" | "reset";
    permission:
      | "camera"
      | "microphone"
      | "photos"
      | "contacts"
      | "notifications"
      | "calendar"
      | "location"
      | "location-always"
      | "media-library"
      | "motion"
      | "reminders";
    bundleId: string;
  };
  "shake": { udid: string; count?: number };
  "stop-all-simulator-servers": { devices?: Array<string> };
  "stop-metro": { port?: number };
  "stop-simulator-server": { udid: string };
  "tv-remote": {
    udid: string;
    button?:
      | "up"
      | "down"
      | "left"
      | "right"
      | "select"
      | "back"
      | "home"
      | "menu"
      | "playPause"
      | "rewind"
      | "fastForward"
      | "next"
      | "previous"
      | "volumeUp"
      | "volumeDown"
      | "mute"
      | Array<
          | "up"
          | "down"
          | "left"
          | "right"
          | "select"
          | "back"
          | "home"
          | "menu"
          | "playPause"
          | "rewind"
          | "fastForward"
          | "next"
          | "previous"
          | "volumeUp"
          | "volumeDown"
          | "mute"
        >;
    repeat?: number;
  };
  "update-argent": { target?: "auto" | "global" | "local" | "both" };
  "view-network-logs": { port?: number; device_id: string; pageIndex?: number | "latest" };
  "view-network-request-details": {
    port?: number;
    device_id: string;
    requestId: string;
    includeBody?: boolean;
  };
}
