import { expect, it } from "vitest";
import * as path from "node:path";
import { format, resolveConfig } from "prettier";
import { createRegistry } from "../src/utils/setup-registry";
import { advertisedSchema, definitionsById } from "./helpers/catalog";

// The SDK's typed tool map is derived from the schemas the tool-server
// advertises. After changing a tool's schema, regenerate it with
// `npx vitest run test/sdk-tool-args.test.ts -u`.
const TARGET = "../../argent/src/tool-args.generated.ts";

type Schema = Record<string, any>;

function key(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function toType(schema: Schema): string {
  if ("not" in schema) return "never";
  if ("const" in schema) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  if (schema.anyOf) return schema.anyOf.map(toType).join(" | ");
  if (Array.isArray(schema.type)) {
    return schema.type.map((type: string) => toType({ ...schema, type })).join(" | ");
  }
  switch (schema.type) {
    case "string":
    case "boolean":
    case "null":
      return schema.type;
    case "number":
    case "integer":
      return "number";
    case "array":
      return `Array<${schema.items ? toType(schema.items) : "unknown"}>`;
    case "object": {
      const required = new Set<string>(schema.required ?? []);
      const props = Object.entries<Schema>(schema.properties ?? {}).map(
        ([name, prop]) => `${key(name)}${required.has(name) ? "" : "?"}: ${toType(prop)};`
      );
      const extra = schema.additionalProperties;
      if (extra && typeof extra === "object") props.push(`[key: string]: ${toType(extra)};`);
      return props.length ? `{ ${props.join(" ")} }` : "Record<string, never>";
    }
    default:
      return "unknown";
  }
}

it("the SDK's tool argument types match the advertised schemas", async () => {
  const entries = [...definitionsById(createRegistry())]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, definition]) => `${key(id)}: ${toType(advertisedSchema(definition)!)};`);

  const source =
    "// Generated by packages/tool-server/test/sdk-tool-args.test.ts. Do not edit.\n\n" +
    `export interface ArgentToolArgs { ${entries.join("\n")} }\n`;
  const target = path.resolve(__dirname, TARGET);
  const formatted = await format(source, {
    ...(await resolveConfig(target)),
    parser: "typescript",
  });

  await expect(formatted).toMatchFileSnapshot(TARGET);
});
