/**
 * Writes the `ArgentToolArgs` interface of `@swmansion/argent/client` from the
 * schemas the tool-server advertises. The build runs it:
 * `node dist/sdk-tool-args.js <output .ts file>`.
 */
import { writeFileSync } from "node:fs";
import { zodObjectToJsonSchema } from "@argent/registry";
import { createRegistry, listToolDefinitions } from "./utils/setup-registry";

type Schema = Record<string, any>;

function key(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function toType(schema: Schema): string {
  if ("const" in schema) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  if (schema.anyOf ?? schema.oneOf) return (schema.anyOf ?? schema.oneOf).map(toType).join(" | ");
  if (schema.allOf) return schema.allOf.map(toType).join(" & ");
  if (Array.isArray(schema.type)) {
    return schema.type.map((type: string) => toType({ ...schema, type })).join(" | ");
  }
  switch (schema.type) {
    case "string":
    case "boolean":
    case "null":
      return schema.type;
    case "number":
    case "integer":
      return "number";
    case "array":
      if (!schema.items) break;
      return `Array<${toType(schema.items)}>`;
    case "object": {
      const required = new Set<string>(schema.required ?? []);
      // A retired param (`not: {}`) is left out, so passing it is an excess-property error.
      const props = Object.entries<Schema>(schema.properties ?? {})
        .filter(([, prop]) => !("not" in prop))
        .map(([name, prop]) => `${key(name)}${required.has(name) ? "" : "?"}: ${toType(prop)};`);
      const extra = schema.additionalProperties;
      if (extra && typeof extra === "object") props.push(`[key: string]: ${toType(extra)};`);
      return props.length ? `{ ${props.join(" ")} }` : "Record<string, never>";
    }
    case undefined:
      if (Object.keys(schema).every((k) => k === "description")) return "unknown";
  }
  throw new Error(`No TypeScript mapping for schema ${JSON.stringify(schema)}`);
}

export function renderSdkToolArgs(): string {
  const entries = [...listToolDefinitions(createRegistry())]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([id, { inputSchema, zodSchema }]) => {
      const schema = inputSchema ?? zodObjectToJsonSchema(zodSchema!);
      return `  ${key(id)}: ${toType(schema)};`;
    });
  return (
    "// Generated by packages/tool-server/src/sdk-tool-args.ts during the build.\n" +
    `export interface ArgentToolArgs {\n${entries.join("\n")}\n}\n`
  );
}

if (require.main === module) {
  const [output] = process.argv.slice(2);
  if (!output) throw new Error("Usage: node dist/sdk-tool-args.js <output .ts file>");
  writeFileSync(output, renderSdkToolArgs());
}
